---

graph_namespace: graph

# The 'purpose' label of preferred nodes
graph_node_purpose: high-mem

# Service Account
# And (if not-empty) the service-account PSP name.
graph_sa: graph
graph_sa_psp: im-unrestricted
