---

graph_namespace: graph

# The 'purpose' label of preferred nodes
# and the name of any Taint that the node may have
# in order to limit application deployments to specific nodes.
graph_node_purpose: bigmem

# Service Account
# And (if not-empty) the service-account PSP name.
graph_sa: graph
graph_sa_psp: im-core-unrestricted
