---

# Use the 'Enterprise Edition' container image?
# You should not set this unless you have a licence from neo4j to run it.
# Setting this to 'yes' adds the '-enterprise' suffix to {{ graph_tag }}.
graph_use_enterprise_edition: no

# Service Account
# And (if not-empty) the service-account PSP name.
graph_sa: graph
graph_sa_psp: im-core-unrestricted

# Number of minutes to allow the graph container's startup probe
# to yield success.
#
# Complex graphs can take a considerable time to initialise
# i.e. 'extract/combination/xchem_dsip/2020-06-26' has been seen to take
# at least 90 minutes to compile the data and a further 80 minutes to
# create indexes and warm-up the cache.
#
# The probe is queried every 60 seconds.
graph_startup_timeout_m: 60

# Wait for volume binding?
# Probably unless multi-zone deployments
# where the PVC will not bind until the 'consumer' pod appears.
wait_for_bind: yes
# Volume binding timeout (seconds)
bind_timeout: 120
