---

# Read cypher script content...
# These variables are used by the graph loader
# where the content (if set) is written to the expected cypher script files.

- name: Set 'once' cypher script content
  set_fact:
    cypher_script_once_content: "{{ lookup('file',  graph_cypher_once_script) }}"
  when: graph_cypher_once_script|string|length > 0

- name: Set 'always' cypher script content
  set_fact:
    cypher_script_always_content: "{{ lookup('file',  graph_cypher_always_script) }}"
  when: graph_cypher_always_script|string|length > 0

- name: Remove pre-existing loader (Job)
  k8s:
    definition: "{{ lookup('template', 'job-loader.yaml.j2') }}"
    state: absent

- name: Deploy Loader (Job)
  k8s:
    definition: "{{ lookup('template', 'job-loader.yaml.j2') }}"
    wait: yes
    wait_timeout: "{{ graph_loader_pod_ready_timeout }}"
    wait_condition:
      type: Complete
