---

# We either remove all the objects we added
# (when the namespace and pvc are pre-provisioned)
# or we just destroy the whole namespace (and the PVC we created).

- name: Remove application objects
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    state: absent
    wait: yes
  loop:
  - secrets
  - job-loader
  - statefulset-graph
  - service-http
  - service-bolt
  - rolebinding
  - role
  - serviceaccount
  when: graph_volume_size_g|int == 0

- name: Remove namespace
  k8s:
    definition: "{{ lookup('template', 'namespace.yaml.j2') }}"
    state: absent
    wait: yes
  when: graph_volume_size_g|int > 0
